import React, { useEffect, useRef, useState } from "react";
import { Outlet, useLocation, useNavigate } from "react-router-dom";
import {
  isSignInWithEmailLink,
  signInWithEmailLink,
  onAuthStateChanged,
} from "firebase/auth";
import { auth } from "../../firebase";
import { isTenantOwner } from "../../auth";

// Cadence POS post-onboarding portal — gated layout shell.
//
// Owners land here from the Cadence platform welcome email AFTER their
// tenant has been provisioned (tenantSetupFinalizeCallable success). The
// welcome email is generated by buildPortalActionCodeSettings in
// functions/saas/auth-claims.js; it carries an optional ?next= query that
// deep-links into a specific portal route (e.g., /portal/port-number for
// pool-number tenants who need to start their port-in immediately).
//
// State machine mirrors TenantSetupLandingScreen but the access gate is
// different: tenant signup uses presence of a setup doc, the portal uses
// the user's auth claims (tenantID + privilege >= 3 via isTenantOwner()).
//
// The actual route content (PortalHomeRoute, PortNumberRoute, etc.) is
// rendered into <Outlet /> below — this layout just owns auth.

const STAGE = {
  LOADING: "loading",
  PROMPT_EMAIL: "prompt_email",
  SIGNING_IN: "signing_in",
  READY: "ready",
  DENIED: "denied",
  ERROR: "error",
  INVALID_LINK: "invalid_link",
};

const EMAIL_LOCALSTORAGE_KEY = "cadence.portal.emailForSignIn";

export function PortalLayout() {
  const [stage, setStage] = useState(STAGE.LOADING);
  const [email, setEmail] = useState("");
  const [user, setUser] = useState(null);
  const [claims, setClaims] = useState(null);
  const [errorMsg, setErrorMsg] = useState("");
  const ranRef = useRef(false);
  const location = useLocation();
  const navigate = useNavigate();

  useEffect(() => {
    if (ranRef.current) return;
    ranRef.current = true;

    const unsub = onAuthStateChanged(auth, async (firebaseUser) => {
      // Path A: user already signed in — force a token refresh so the
      // tenant-owner claims (stamped by tenantSetupFinalizeCallable) are
      // current, then gate by isTenantOwner.
      if (firebaseUser) {
        setUser(firebaseUser);
        setEmail(firebaseUser.email || "");
        try {
          const tokenResult = await firebaseUser.getIdTokenResult(true);
          setClaims(tokenResult.claims);
          if (isTenantOwner(tokenResult.claims)) {
            setStage(STAGE.READY);
            handleEmailLinkRedirect();
          } else {
            setStage(STAGE.DENIED);
          }
        } catch (err) {
          setErrorMsg(err?.message || "Failed to load your account.");
          setStage(STAGE.ERROR);
        }
        return;
      }

      // Path B: user not signed in. If the URL is a Firebase email-link,
      // try to complete sign-in using the stashed email.
      if (isSignInWithEmailLink(auth, window.location.href)) {
        const stored = window.localStorage.getItem(EMAIL_LOCALSTORAGE_KEY);
        if (stored) {
          await completeSignIn(stored);
        } else {
          setStage(STAGE.PROMPT_EMAIL);
        }
        return;
      }

      // Path C: not signed in, not an email-link. The portal is invite-only;
      // no anonymous access path.
      setStage(STAGE.INVALID_LINK);
    });

    return unsub;
  }, []);

  // If the welcome email carried ?next=/portal/<path> and the user landed on
  // /portal/?next=..., navigate them to the requested sub-route once they're
  // signed in. This is how pool-number tenants land directly on /port-number.
  function handleEmailLinkRedirect() {
    const params = new URLSearchParams(window.location.search);
    const nextRaw = params.get("next");
    if (!nextRaw) return;
    let next;
    try {
      next = decodeURIComponent(nextRaw);
    } catch {
      return;
    }
    // Only honor in-app paths under /portal to avoid open-redirect risk.
    if (!next.startsWith("/portal")) return;
    if (next === location.pathname) return;
    navigate(next, { replace: true });
  }

  async function completeSignIn(emailToUse) {
    setStage(STAGE.SIGNING_IN);
    setErrorMsg("");
    try {
      await signInWithEmailLink(auth, emailToUse, window.location.href);
      window.localStorage.removeItem(EMAIL_LOCALSTORAGE_KEY);
      // onAuthStateChanged above fires next, which runs the claims gate.
    } catch (err) {
      const code = err?.code || "";
      const msg = err?.message || "Sign-in failed.";
      setErrorMsg(code ? `${code}: ${msg}` : msg);
      setStage(STAGE.ERROR);
    }
  }

  function handleEmailSubmit(e) {
    e.preventDefault();
    const trimmed = email.trim().toLowerCase();
    if (!trimmed) return;
    window.localStorage.setItem(EMAIL_LOCALSTORAGE_KEY, trimmed);
    void completeSignIn(trimmed);
  }

  if (stage === STAGE.LOADING || stage === STAGE.SIGNING_IN) {
    const label =
      stage === STAGE.SIGNING_IN ? "Signing you in…" : "Loading…";
    return (
      <div className="centerScreen">
        <div className="card">
          <h1 className="cardTitle">Cadence POS</h1>
          <p className="cardSubtitle">{label}</p>
        </div>
      </div>
    );
  }

  if (stage === STAGE.PROMPT_EMAIL) {
    return (
      <div className="centerScreen">
        <form className="card" onSubmit={handleEmailSubmit}>
          <h1 className="cardTitle">Confirm your email</h1>
          <p className="cardSubtitle">
            For security, please re-enter the email you used to receive this
            portal link.
          </p>
          <label className="fieldLabel">Email</label>
          <input
            type="email"
            className="textInput"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            autoFocus
            autoComplete="email"
          />
          {errorMsg && <div className="errorText">{errorMsg}</div>}
          <button type="submit" className="primaryButton">
            Continue
          </button>
        </form>
      </div>
    );
  }

  if (stage === STAGE.INVALID_LINK) {
    return (
      <div className="centerScreen">
        <div className="card">
          <h1 className="cardTitle">Portal access required</h1>
          <p className="cardSubtitle">
            This portal is reachable only through a link emailed to a Cadence
            POS owner. If you need access, sign in to the POS app and request
            a new portal link from your Subscription settings.
          </p>
        </div>
      </div>
    );
  }

  if (stage === STAGE.DENIED) {
    return (
      <div className="centerScreen">
        <div className="card">
          <h1 className="cardTitle">Not authorized</h1>
          <p className="cardSubtitle">
            Signed in as <strong>{email}</strong>. This portal is restricted
            to tenant owners. If you believe this is in error, sign out and
            try the link from your owner's email again.
          </p>
        </div>
      </div>
    );
  }

  if (stage === STAGE.ERROR) {
    return (
      <div className="centerScreen">
        <div className="card">
          <h1 className="cardTitle">Something went wrong</h1>
          <p className="cardSubtitle">{errorMsg}</p>
          <p className="helperText">
            If your link is expired, sign in to the POS app and request a new
            portal link from Subscription settings.
          </p>
        </div>
      </div>
    );
  }

  // STAGE.READY — render the matched sub-route. Children receive the
  // tenant context via React Router's Outlet context.
  return <Outlet context={{ user, claims, email }} />;
}
