/* eslint-disable */
// Settings + status/discount prototypes shared between the tenant app and
// Cloud Functions. This file MUST stay free of imports from outside
// src/shared/ — the firebase predeploy hook copies src/shared/ →
// functions/shared/ so SaaS callables can read SETTINGS_OBJ when
// bootstrapping a new tenant's first store.
//
// SETTINGS_OBJ is kept verbatim from its original location so the tenant
// app's fallback path (`useSettingsStore((s) => s.settings) || SETTINGS_OBJ`)
// keeps producing the same result. Bonita-specific strings + IDs are
// substituted and regenerated by the bootstrap callable at tenant
// provision time — not here.

const DARK_TEXT = "rgb(20, 20, 20)";

export const DISCOUNT_TYPES = {
  percent: "%",
  dollar: "$",
};

export const NONREMOVABLE_STATUSES = [

  {
    id: "newly_created",
    label: "Newly Created",
    textColor: "white",
    backgroundColor: "red",
    removable: false,
    requireWaitTime: false,
    hidden: false,
  },

  {
    id: "work_in_progress",
    textColor: DARK_TEXT,
    backgroundColor: "rgb(192,192,192)",
    label: "Work in Progress",
    removable: false,
    hidden: false,
  },
  {
    id: "pickup",
    textColor: "white",
    backgroundColor: "purple",
    label: "Pickup",
    removable: false,
    hidden: false,
  },
  {
    id: "delivery",
    textColor: "white",
    backgroundColor: "purple",
    label: "Delivery",
    removable: false,
    hidden: false,
  },
  {
    id: "service",
    textColor: "rgb(71, 71, 71)",
    backgroundColor: "rgb(192,192,192)",
    label: "Service",
    removable: false,
    requireWaitTime: false,
    hidden: false,
  },
  {
    id: "is_order_part_for_customer",
    textColor: "rgb(38,38,38)",
    backgroundColor: "red",
    label: "Order Item for Customer",
    removable: false,
    hidden: false,
  },
  {
    id: "finished",
    textColor: "white",
    backgroundColor: "green",
    label: "Finished",
    removable: false,
    requireWaitTime: false,
    hidden: false,
  },
  {
    id: "finished_and_paid",
    textColor: "white",
    backgroundColor: "green",
    label: "Finished & Paid",
    removable: false,
    requireWaitTime: false,
    hidden: false


  },
  {
    id: "part_ordered",
    textColor: "white",
    backgroundColor: "orange",
    label: "Item Ordered",
    removable: false,
    hidden: true,
  },



  {
    id: "finished_and_paid",
    label: "Finished & Paid",
    textColor: "white",
    backgroundColor: "green",
    removable: false,
    requireWaitTime: false,
    systemOwned: true,
    hidden: false,
  },

];

export const SETTINGS_OBJ = {
  laborRateByHour: 9000,
  statuses: [
    ...NONREMOVABLE_STATUSES,
    {
      id: "finished",
      textColor: "white",
      backgroundColor: "green",
      label: "Finished - No Auto Text",
      removable: true,
      requireWaitTime: false,
    },
    {
      id: "1334453",
      textColor: "white",
      backgroundColor: "orange",

      label: "Order Item for Customer",
      removable: true,
    },

    {
      id: "ek3rkeng",
      textColor: "white",
      backgroundColor: "blue",

      label: "Messaging Customer",
      removable: true,
    },
  ],
  quickItemButtons: [
    { id: "38trrneg", name: "Tune-Up", parentID: null, items: [], removable: true },
    { id: "38trrdfdneg", name: "Tube", parentID: null, items: ["3Rh6JaP75v1esbywt18E", "9xCMXA89wZeAt1IBfLoU"], removable: true },
    { id: "38trrsdfneg", name: "Tire", parentID: null, items: [], removable: true },
    { id: "38trdfdrneg", name: "Tube & Tire", parentID: null, items: [], removable: true },
    { id: "38trdfadrneg", name: "Brakes", parentID: null, items: [], removable: true },
    { id: "38tradfdrneg", name: "Cable", parentID: null, items: ["Rcr7QgWyNPapdoYVuS7P", "9xCMXA89wZeAt1IBfLoU"], removable: true },
    { id: "38trrnebfdgdg", name: "Shifting", parentID: null, items: ["iBFklersI6UmzR8x1ADn", "Rcr7QgWyNPapdoYVuS7P"], removable: true },
    { id: "38trrnadfvceg", name: "Drivetrain", parentID: null, items: [], removable: true },
    { id: "38trsadgdvdrneg", name: "Spoke", parentID: null, items: [], removable: true },
    { id: "38trerfedgbdrneg", name: "Cleaning", parentID: null, items: [], removable: true },
    { id: "38trrfrdggdneg", name: "Scooter", parentID: null, items: [], removable: true },
    { id: "bnfdeqw", name: "Pickup/Delivery", parentID: null, items: [], removable: true },
    { id: "34trhrg", name: "Diagnostics", parentID: null, items: [], removable: true },
    { id: "labor", name: "$Labor", parentID: null, items: [], removable: false },
    { id: "item", name: "$Item", parentID: null, items: [], removable: false },
    { id: "common", name: "Common", parentID: null, items: [], removable: false },
  ],
  // quickButtons: [],
  // colors:
  bikeBrands: ["Trek", "Specialized", "Sun", "Marin", "Cannondale", "Jamis"],
  bikeBrandsName: "Bikes",
  bikeOptionalBrands: ["Euphree", "Lectric", "Hiboy", "Ridstar", "Velowave"],
  bikeOptionalBrandsName: "E-bikes",
  allBrands: ["Cannondale", "Euphree", "Hiboy", "Jamis", "Lectric", "Marin", "Ridstar", "Specialized", "Sun", "Trek", "Velowave"],
  allDescriptions: ["Cruiser", "E-Bike", "Hybrid", "Road Bike"],
  discounts: [
    {
      id: "1333k",
      name: "50% Off Item",
      value: "50",
      type: DISCOUNT_TYPES.percent,
    },
    {
      id: "193j3k",
      name: "10% Off Item",
      value: "10",
      type: DISCOUNT_TYPES.percent,
    },
    {
      id: "394393",
      name: "20% Off Item",
      value: "20",
      type: DISCOUNT_TYPES.percent,
    },
    {
      id: "394393d",
      name: "30% Off Item",
      value: "30",
      type: DISCOUNT_TYPES.percent,
    },
    {
      id: "3943933",
      name: "40% Off Item",
      value: "40",
      type: DISCOUNT_TYPES.percent,
    },
    {
      id: "394393343",
      name: "50% Off Item",
      value: "50",
      type: DISCOUNT_TYPES.percent,
    },
    {
      id: "3k3nh",
      name: "2-bike purchase, $100 Off Each Bike",
      value: "10000",
      type: DISCOUNT_TYPES.dollar,
    },
    {
      id: "343gfg",
      name: "$10 Off",
      value: "1000",
      type: DISCOUNT_TYPES.dollar,
    },
  ],
  waitTimeLinkedStatus: {},
  waitTimeLabelCategories: [
    {
      id: 'dkfjdk',
      label: "First half {weekDayName}"
    },
    { id: 'ndfkdaj', label: 'Second half {weekDayName}' }
  ],
  waitTimes: [
    {
      id: "34j3kj3dfdfgfkj3",
      label: "Waiting",
      maxWaitTimeDays: 0,
    },
    {
      id: "34jngfedde3kj3kj3",
      label: "Today",
      maxWaitTimeDays: 0, removable: true,
    },
    {
      id: "34j3kjdww3kj3",
      label: "Tomorrow",
      maxWaitTimeDays: 1, removable: true,
    },
    {
      id: "34j3kj3",
      label: "1-2 Days",
      maxWaitTimeDays: 2, removable: true,
    },
    {
      id: "34j3kj33",
      label: "2-3 Days",
      maxWaitTimeDays: 3, removable: true,
    },
    {
      id: "34j3kj3kj3",
      label: "3-5 Days",
      maxWaitTimeDays: 5, removable: true,
    },
    {
      id: "34j3kj33kj3n",
      label: "1 Week",
      maxWaitTimeDays: 7, removable: true,
    },
    {
      id: "34j3kj3,rkjk",
      label: "1-2 Weeks",
      maxWaitTimeDays: 14, removable: true,

    },
    {
      id: "34j3kj3vnkd",
      label: "No Estimate",
      maxWaitTimeDays: 0,
      removable: false,
    },
  ],
  storeHours: {
    standard: [
      {
        name: "Monday",
        id: "dkfjdkfn",
        open: "10:00 AM",
        close: "6:00 PM",
        isOpen: true,
      },
      {
        name: "Tuesday",
        id: "dkfjdkf3r3n",
        open: "10:00 AM",
        close: "6:00 PM",
        isOpen: true,
      },
      {
        name: "Wednesday",
        id: "dkfjdkfdkfjdkn",
        open: "10:00 AM",
        close: "6:00 PM",
        isOpen: true,
      },
      {
        name: "Thursday",
        id: "dkfjdkf34rjk3n",
        open: "10:00 AM",
        close: "6:00 PM",
        isOpen: true,
      },
      {
        name: "Friday",
        id: "dkfjdkfkenjrken",
        open: "10:00 AM",
        close: "6:00 PM",
        isOpen: true,
      },
      {
        name: "Saturday",
        id: "dkfjdk3krjfn",
        open: "10:00 AM",
        close: "6:00 PM",
        isOpen: true,
      },
      {
        name: "Sunday",
        id: "dkfjdkf3nrkejn",
        open: "10:00 AM",
        close: "6:00 PM",
        isOpen: true,
      },
    ],
    special: [
      {
        name: "4th of July",
        dateMillies: 123434455544,
        id: "dkfjdkf3nrk333ejn",
        open: "10:00 AM",
        close: "6:00 PM",
        isOpen: false,
      },
    ],
  },
  storeInfo: {
    displayName: "Bonita Bikes LLC",
    street: "9102 Bonita Beach Rd SE",
    unit: "",
    city: "Bonita Springs",
    state: "Florida",
    zip: "34135",
    phone: "2393369177",
    supportEmail: "",
    officeEmail: "",
    textingNumber: "",
    storeLogo: "",
  },
  receiptSetup: {
    includeFieldsInReceipt: ["displayName", "street", "city", "state", "phone"],
  },
  printers: {

  },
  labelLayouts: [],
  labelTemplates: {},
  quickPrintLayouts: [],
  defaultLabelSize: { name: '2.25" x 1.25"', width: 464, height: 254 },
  autoSMSIntakeReceipt: true,
  autoEmailIntakeReceipt: true,
  autoPrintIntakeReceipt: true,
  autoSMSSalesReceipt: true,
  autoEmailSalesReceipt: true,
  autoPrintSalesReceipt: true,
  shopContactBlurb: "9102 Bonita Beach Rd SE\nBonita Springs, FL\n(239) 291-9396\nsupport@bonitabikes.com\nwww.bonitabikes.com",
  intakeBlurb: "This ticket is an estimate, and MAY NOT INCLUDE ALL ITEMS FOR THE SERVICE. We will add items as discussed, and call for unforseen major additions.",
  thankYouBlurb: "Thanks you for visiting Bonita Bikes! \nWe value your business and satisfaction with our services. \n\nPlease call or email anytime, we look forward to seeing you again.",
  waitTimeBlurbWithEstimate: "Wait times are a BEST ESTIMATE only; We will call/text/email when service is complete!",
  waitTimeBlurbWithoutEstimate: "We do not currently have an estimate. We will call/text/email when service is complete!",
  bikeDescriptions: ["Hybrid", "E-Bike", "Cruiser", "Road Bike"],
  partSources: ["JBI", "QBP", "Amazon", "Ebay", "Customer"],
  allPartSources: ["JBI", "QBP", "Amazon", "Ebay", "Customer"],
  smsConversationLockTimeout: 2, //days
  activeLoginTimeoutSeconds: 7,
  userInactivityTimeout: 120,
  idleLoginTimeoutHours: 24,
  salesTaxPercent: 6.5,
  acceptChecks: true,
  userPinStrength: 2,
  cardRefundFeePercent: 3,
  useCardFee: false,
  cardFeePercent: 3,
  cardFeeRefund: false,
  allowStaffPhoneReply: true,
  lockScreenWhenUserLogsOut: false,
  useFacialRecognition: true,
  faceRecognitionThreshold: 0.55,
  tenantID: "1234",
  storeID: "999",
  users: [],
  cardReaders: [],
  selectedCardReaderObj: {
    label: "",
    id: "",
  },
  defaultPayrollTimeFrame: {
    "begin": 'lastFriday',
    "end": 'thisThursday',
  },
  autoConnectToCardReader: "true",
  amazonExtension: {
    enabled: true,
    storeId: 999, // Will be auto-generated from tenantID_storeID
    shippingAddress: {
      fullName: "",
      addressLine1: "",
      addressLine2: "",
      city: "",
      state: "",
      zipCode: "",
      phoneNumber: "",
    },
    lastSync: null,
    extensionVersion: "1.0.0",
    autoSync: true,
    features: {
      autoFill: true,
      simplifyUI: true,
      hideAds: true,
      quickSearch: true,
    },
  },
  smsTemplates: [
    {
      id: "finished_sms",
      label: "Finished",
      content: "Hi {firstName}, your {brand} {description} is ready for pickup! Your total is {totalAmount}. We're open {storeHours}. Call us at {storePhone} with any questions.",
      type: "",
      order: 0,
      showInChat: true,
      removable: false,
    },
    {
      id: "finished_multiple_items_sms",
      label: "Finished - Multiple Items",
      content: "Hi {firstName}, your {brands} are ready for pickup! Your total is {totalAmount}. We're open {storeHours}. Call us at {storePhone} with any questions.",
      type: "",
      order: 0,
      showInChat: true,
      removable: false,
    },
    {
      id: "fkdnfdfd",
      label: "Part Ordered",
      content: "Hi {firstName}, we've ordered a part for your {brand} {description}. As soon as we get the part we will proceed with the requested service. Call us at {storePhone} with any questions.",
      type: "",
      order: 0,
      showInChat: true,
      removable: true,
    },
    {
      id: "default_sms_sale_receipt",
      label: "Sale Receipt",
      content: "🎉 Thanks for your purchase, {firstName}! Your total was {total}. Here's your receipt: {link}\n\nWe appreciate your business! — {storeName} 🚲",
      type: "saleReceipt",
      order: 0,
      showInChat: false,
      removable: false,
    },
    {
      id: "default_sms_refund_receipt",
      label: "Refund Receipt",
      content: "Hey {firstName}, your refund of {total} has been processed. Here's your receipt: {link}\n\nThank you! — {storeName}",
      type: "refundReceipt",
      order: 0,
      showInChat: false,
      removable: false,
    },
    {
      id: "default_sms_intake_receipt",
      label: "Intake Receipt",
      content: "🔧 Hey {firstName}! Your {brand} {description} is checked in and in good hands. Here's your receipt: {link}\n\nTrack your workorder: {workorderLink}\n\nWe'll keep you posted! — {storeName} 🚲",
      type: "intakeReceipt",
    },
    {
      id: "default_sms_credit_receipt",
      label: "Credit Receipt",
      content: "💰 Hey {firstName}! A store credit of {amount} has been added to your account. Here's your receipt: {link}\n\nThank you! — {storeName}",
      type: "creditReceipt",
      removable: false,
    },
    {
      id: "default_sms_giftcard_receipt",
      label: "Gift Card Receipt",
      content: "🎁 Hey {firstName}! A gift card of {amount} has been loaded to your account. Here's your receipt: {link}\n\nThank you! — {storeName}",
      type: "giftCardReceipt",
      removable: false,
      order: 0,
      showInChat: false,
    },
  ],
  autoCustomerNoteTexts: [],
  translateStarters: [
    {
      id: "greeting_1",
      label: "Greeting",
      text: "Hello, welcome to our store. If you have a translation app on your phone, we can use it together to help you with whatever you need. Please show us your screen and we will type here.",
      language: "en",
    },
  ],
  emailGreeting: "{storeLogo}\nHi {firstName}, thanks for choosing {storeDisplayName}!",
  emailFooter: "{storeDisplayName}\n{storeStreet}, {storeCity}, {storeState} {storeZip}\n{storePhone}",
  emailGreetingAlign: "center",
  emailFooterAlign: "center",
  emailLogoWidth: 180,
  emailGreetingColorObj: { textColor: "white", backgroundColor: "#2E7D32", label: "Green" },
  emailSignature: { segments: [], imageUrl: "" },
  emailTemplates: [
    {
      id: "finished_email",
      label: "Finished",
      subject: "Your bike is ready! - {storeName}",
      message: "Great news - your {brand} {description} is ready for pickup!\n\nItems completed:\n{lineItems}\n\n{customerNotes}\n\nTotal: {totalAmount}\n\nPlease note: we do not monitor this inbox during the day, so responses may be delayed. You are better off calling the shop directly at {storePhone}.",
      action: "",
      actionColorObj: { textColor: "white", backgroundColor: "green", label: "Green" },
      type: "",
      removable: false,
    },
    {
      id: "finished_multiple_items_email",
      label: "Finished - Multiple Items",
      subject: "Your bikes are ready! - {storeName}",
      message: "Great news - your {brands} are ready for pickup!\n\nTotal: {totalAmount}\n\nPlease note: we do not monitor this inbox during the day, so responses may be delayed. You are better off calling the shop directly at {storePhone}.",
      action: "",
      actionColorObj: { textColor: "white", backgroundColor: "green", label: "Green" },
      type: "",
      removable: false,
    },
    {
      id: "default_workorder_complete",
      label: "Workorder Complete",
      subject: "Your bike is ready! - {storeName}",
      message: "Great news - your {brand} {description} is ready for pickup!\n\nItems completed:\n{lineItems}\n\n{customerNotes}\n\nTotal: {totalAmount}\n\nPlease note: we do not monitor this inbox during the day, so responses may be delayed. You are better off calling the shop directly at {storePhone}.",
      action: "",
      actionColorObj: { textColor: "white", backgroundColor: "green", label: "Green" },
      type: "",
    },
    {
      id: "default_payroll_summary",
      label: "Payroll Summary",
      subject: "Payroll Summary - {employeeName} - {payPeriod}",
      message: "Here is your work summary for {payPeriod}:\n\n{dailyBreakdown}\n\nTotal Hours: {totalHours}\nPay Rate: {payRate}\nTotal Pay: {totalPay}",
      action: "",
      actionColorObj: { textColor: "white", backgroundColor: "green", label: "Green" },
      type: "",
    },
    {
      id: "default_email_sale_receipt",
      label: "Sale Receipt",
      subject: "Your receipt from {storeName}",
      message: "Thank you for your purchase! Your total was {total}.\n\nWe appreciate your business and hope to see you again soon!",
      action: "View Receipt",
      actionColorObj: { textColor: "white", backgroundColor: "green", label: "Green" },
      type: "saleReceipt",
    },
    {
      id: "default_email_refund_receipt",
      label: "Refund Receipt",
      subject: "Your refund from {storeName}",
      message: "Your refund of {total} has been processed.\n\nIf you have any questions, please don't hesitate to reach out.",
      action: "View Refund Receipt",
      actionColorObj: { textColor: "white", backgroundColor: "green", label: "Green" },
      type: "refundReceipt",
    },
    {
      id: "default_email_intake_receipt",
      label: "Intake Receipt",
      subject: "Your {brand} is checked in - {storeName}",
      message: "Your {brand} {description} has been checked in and is in good hands. Here's a copy of your intake receipt for your records.\n\nWe'll keep you updated on the progress. If you have any questions in the meantime, don't hesitate to reach out!",
      action: "View Intake Receipt",
      actionColorObj: { textColor: "white", backgroundColor: "green", label: "Green" },
      type: "intakeReceipt",
    },
    {
      id: "default_email_credit_receipt",
      label: "Credit Receipt",
      subject: "Store credit added - {storeName}",
      message: "A store credit of {amount} has been added to your account.\n\nThank you for your business!",
      action: "View Credit Receipt",
      actionColorObj: { textColor: "white", backgroundColor: "green", label: "Green" },
      type: "creditReceipt",
    },
    {
      id: "default_email_giftcard_receipt",
      label: "Gift Card Receipt",
      subject: "Gift card loaded - {storeName}",
      message: "A gift card of {amount} has been loaded to your account.\n\nThank you!",
      action: "View Gift Card Receipt",
      actionColorObj: { textColor: "white", backgroundColor: "green", label: "Green" },
      type: "giftCardReceipt",
    },
  ],
  statusAutoText: [],
  noteHelpers: [{
    id: 'position',
    label: 'Position',
    items: [
      { id: 'pos1', buttonLabel: 'Front', text: '' },
      { id: 'pos2', buttonLabel: 'Rear', text: '' },
    ]
  },
  {
    id: 'brakes',
    label: 'Brakes',
    items: [
      { id: 'brk1', buttonLabel: 'Squealing', text: '' },
      { id: 'brk2', buttonLabel: 'Broken', text: '' },
      { id: 'brk3', buttonLabel: 'Very contaminated', text: '' },
    ]
  },
  {
    id: 'tires',
    label: 'Tires',
    items: [
      { id: 'tir1', buttonLabel: 'Worn', text: '' },
      { id: 'tir2', buttonLabel: 'Broken', text: '' },
    ]
  },
  {
    id: 'tube',
    label: 'Tube',
    items: [
      { id: 'tub1', buttonLabel: 'Slow leak', text: '' },
    ]
  },
  {
    id: 'cable',
    label: 'Cables',
    items: [
      { id: 'cab1', buttonLabel: 'Brake', text: '' },
      { id: 'cab2', buttonLabel: 'Shifter', text: '' },
      { id: 'cab3', buttonLabel: 'Corroded', text: '' },
      { id: 'cab4', buttonLabel: 'Kinked', text: '' },
    ]
  },
  {
    id: 'chain',
    label: 'Chain',
    items: [
      { id: 'chn1', buttonLabel: 'Stretched', text: '' },
      { id: 'chn2', buttonLabel: 'Corroded', text: '' },
      { id: 'chn3', buttonLabel: 'Twisted', text: '' },
    ]
  },
  {
    id: 'gears',
    label: 'Gears',
    items: [
      { id: 'ger1', buttonLabel: 'Worn', text: '' },
      { id: 'ger2', buttonLabel: 'Corroded', text: '' },
    ]
  },
  {
    id: 'wheels',
    label: 'Wheels',
    items: [
      { id: 'whl1', buttonLabel: 'Spokes', text: '' },
      { id: 'whl2', buttonLabel: 'Damaged', text: '' },
    ]
  },
  {
    id: 'shifter',
    label: 'Shifter',
    items: [
      { id: 'shf1', buttonLabel: 'Gummed', text: '' },
      { id: 'shf2', buttonLabel: 'Broken', text: '' },
      { id: 'shf3', buttonLabel: 'Try to recover', text: '' },
    ]
  },
  {
    id: 'customer',
    label: 'Customer Request',
    items: [
      { id: 'cst1', buttonLabel: 'Customer Request', text: '' },
    ]
  },
  ],
  noteHelpersTarget: "intakeNotes",
  customerQuickNotes: [{
    id: 'tune',
    label: 'Tune-up',
    items: [ // usese QUICK_CUSTOMER_NOTE_ITEM_PROTO
      {
        id: 'dndkjk',
        buttonLabel: "Standard",
        text: `- tuned shifting
      - tuned/adjusted brakes
      - cleaned & lubed chain
      - cleaned frame`
      }
    ]
  },
  {
    id: 'tube',
    label: 'Tubes',
    items: [
      {
        id: "dknfdk",
        buttonLabel: "Small sharp",
        text: `Did some stuff`
      }
    ]
  }
  ],
  nextWorkorderCounter: 1,
  nextSaleCounter: 1,
};

