const fs = require("fs");
const path = require("path");

const version = Date.now().toString();

fs.writeFileSync(
  path.join(__dirname, "..", "public", "version.json"),
  JSON.stringify({ version }) + "\n"
);

fs.writeFileSync(
  path.join(__dirname, "..", "src", "buildVersion.js"),
  `// Auto-generated by scripts/update-version.js before each production build.\n// Do not edit manually — this file is overwritten on \`npm run build\`.\nexport const BUILD_VERSION = "${version}";\n`
);

console.log("Build version set to:", version);
