export const DEFAULT_SALE_LABELS = {
  title: "SALES RECEIPT",
  subtotal: "Subtotal",
  discount: "Discount",
  salesTax: "Sales Tax",
  cardFee: "Card Fee",
  total: "TOTAL",
  itemHeader: "Item",
  qtyHeader: "Qty",
  priceHeader: "Price",
  totalHeader: "Total",
  payments: "Payments",
  cash: "Cash",
  card: "Card",
  auth: "Auth",
  tendered: "Tendered",
  change: "Change",
  amountPaid: "Amount Paid",
  notesHeader: "Notes for our customer:",
  customer: "Customer",
  contact: "Contact",
  woNumber: "WO #",
  discountPrefix: "Discount",
  notePrefix: "Note",
};
